name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc

    - name: Compile tests
      shell: bash
      run: |
        g++ -std=c++17 student_database.cpp tests.cpp third_party/googletest/src/gtest-all.cc \
        -I third_party/googletest/include -pthread -o tests.exe

    - name: Run tests
      shell: bash
      run: ./tests.exe