name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake libgtest-dev

    - name: Build tests
      run: |
        # Сборка GoogleTest прямо из исходников
        g++ -std=c++17 student_database.cpp tests.cpp \
        /usr/src/googletest/googletest/src/gtest-all.cc \
        -I /usr/src/googletest/googletest/include -pthread -o tests

    - name: Run tests
      run: ./tests
